name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore:') && !contains(github.event.head_commit.message, 'documentation:')"
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Pack NuGet package
      run: |
        dotnet nuget pack ./src/FluentMigrator.Generator.Core.nuspec \
        -Version ${{ steps.gitversion.outputs.majorMinorPatch }} \
        -OutputDirectory ./artifacts

    - name: Push NuGet package
      if: github.ref == 'refs/heads/master'
      run: |
        dotnet nuget push "./artifacts/FluentMigrator.Generator.Core.${{ steps.gitversion.outputs.majorMinorPatch }}.nupkg" \
        --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
        release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
        body: Release ${{ steps.gitversion.outputs.majorMinorPatch }}

    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Nuget Package"
        path: "./artifacts/FluentMigrator.Generator.Core.${{ steps.gitversion.outputs.majorMinorPatch }}.nupkg"
